language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
install:
- npm install
script:
- gulp test
env:
  global:
    secure: Igo4tyDB4eXPu1+a+lh+yCwVELag7XjDMohdkHWen5BMuGDrWZqeaQTqM/pl/aiRWGQmMHIqxC34L1zFUjOTyw/04NJti3rGoyFEkWOuVf1ahwXuN9NftPMX7J+6GaVhNfaazVr1GwvuQekNuafV4DvfuTF5bpDgAzAgBe/JDUbHOBGzk9LEzO+ASdolr7Fby4wOTwN4qwdHE+tZonMcPDXdOsXLpUjbMhs7iu9i9fU+ZXMSj/hW2bSihqUOeLabHluegRKvcB46E2VqCIXwtlOElQNSu0+qboEarKk/RVbaCSnHThVbqtPgTgd9B7pgalpMkKSri2lgQeih/zew6p4PgGVW8TCUyfFoU4yN1+XpVVR22dnosZrSMfHaBd6lXotNtM3DNCcPbYyK66GcYTWuxaWTtjwh2k8SdsgIk/Xx0fLBZENq3KIFxeFH86WVJkM3uYpyviuq1vB5lLSXXQOTTavhiQZEakugjpNNwKcL2Mm8PI/PjqsKMXp2O9+2xpkN9FSvrL+7BEkEbAWJ1ZTtKr4w850NVGdSXCqDmanMmpiXdQ03I9mieSxI0HygdMaNb79IqhkP5+0EFGDFD93JDa5PsN7TBj9VAgGwwQzPHZZJOn++Ecwl3zqETAjRwqmPf3UiCgJyfYjridymxHtQDx7GbFMSDJVNnVDhWNQ=
